version: "3.9"
services:
  mysqlj:
    image: mysql:8.0
    command: mysqld --max-connections=256 --sql_mode="NO_ZERO_IN_DATE,NO_ENGINE_SUBSTITUTION"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    volumes:
      - mysqldataj:/usr/share/mysql/data
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
#  javastarter:
#    build: .
#    ports:
#      - "8081:8080"
#    environment:
#      - MYSQL_HOST=mysqlj
#      - MYSQL_PASSWORD=password
#    depends_on:
#      - "mysqlj"
volumes:
  mysqldataj:
    driver: local
